config/routes.rb
Rails.application.routes.draw do
  get 'report/index'
  get 'report/points', to: "report#points"
  resources :points
  get 'cinema_place/index'
  get 'cinema_place/show'
  get 'cinema_place/new'
  post '/cinema_places/process', to: "cinema_places#process_place", as: 'process_cinema_place'
  resources :movies do
    resources :califications
  end
  resources :products
  resources :multiplexes do
    resources :cinemas do
      resources :cinema_place
      resources :product_orders, except: [:show, :index]
    end
  end
  resources :product_orders, only: [:show, :index]
  resources :employees
  resources :clients
  get 'welcome/index'
  root to: 'welcome#index'
  devise_for :users, controllers: { registrations: "registrations" }
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
end

app/models/calification.rb
class Calification < Primary2Record
  belongs_to :movie, foreign_key: "movie_id"
end

app/models/cinema.rb
class Cinema < PrimaryRecord
  belongs_to :multiplex, foreign_key: "multiplex_id"
  has_many :cinema_places
  before_create :set_multiplex_number
  has_one :movie, foreign_key: "movie_id"

  def available_places
    cinema_places.where(state: :free).count
  end

  def general_places
    cinema_places.where(state: :free, cinema_place_type: :general).count
  end

  def preference_places
    cinema_places.where(state: :free, cinema_place_type: :preference).count
  end

  private
  def set_multiplex_number
    size = multiplex.cinemas.count
    self.multiplex.update(cinemas_number: size)
  end
end

app/models/cinema_place.rb
class CinemaPlace < PrimaryRecord
  belongs_to :cinema
  has_one :user, foreign_key: "user_id"
  has_many :tickets


  def processing?
    tickets.where(state: :processing).present?
  end

  def preference?
    cinema_place_type == "preference"
  end

  def free?
    !tickets.where(state: [:processing, :busy]).present?
  end

end

app/models/client.rb
class Client < PrimaryRecord
  belongs_to :user
end

app/models/employee.rb
class Employee < PrimaryRecord
  belongs_to :user
  has_one :multiplex, class_name: 'Multiplex',foreign_key: "mutiplex_id"
end

app/models/movie.rb
class Movie < Primary2Record
  has_many :califications
end

app/models/multiplex.rb
class Multiplex < PrimaryRecord
  has_many :cinemas, class_name: "Cinema"

  def set_cinemas_number
    update(cinemas_number: cinemas.count)
  end
end

app/models/point.rb
class Point < PrimaryRecord
  belongs_to :product_order
  belongs_to :client
end

app/models/primary_record.rb
class PrimaryRecord < ApplicationRecord
  self.abstract_class = true

  connects_to database: { writing: :primary, reading: :primary }
end

app/models/product.rb
class Product < PrimaryRecord
end

app/models/product_item.rb
class ProductItem < PrimaryRecord
  belongs_to :product
  belongs_to :product_order, foreign_key: 'product_order_id', optional: true

  def value
    product.price.to_i
  end
end

app/models/product_order.rb
class ProductOrder < PrimaryRecord
  include AASM
  belongs_to :multiplex
  belongs_to :client
  has_many :product_items
  accepts_nested_attributes_for :product_items, allow_destroy: true, reject_if: :all_blank
  validates_associated :product_items
  has_many :tickets

  aasm column: 'state' do
    state :created, initial: true
    state :paid

    event :paid do
      transitions from: :created, to: :paid
    end
  end

  def paid?
    state == "paid"
  end

  private

end

app/models/ticket.rb
class Ticket < ApplicationRecord
  belongs_to :cinema_place, foreign_key: "cinema_place_id"
  belongs_to :product_order, foreign_key: "product_order_id"
  include AASM
  aasm column: 'state' do
    state :processing, initial: true
    state :busy
    state :finalized

    event :process do
      transitions from: :free, to: :processing
    end

    event :complete do
      transitions from: :processing, to: :busy
    end

    event :clean do
      transitions from: :busy, to: :free
    end

    event :finish do
      transitions to: :finalized
    end
  end
end

app/models/user.rb
class User < PrimaryRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  has_one :client
  has_one :employee

  def full_name
    return "#{name} #{last_name}"
  end

  def has_completed_signed?
    if is_employee?
      return employee.present?
    end
    true
  end

  def is_employee?
    self.role == "Employee"
  end

  def is_client?
    self.role == "Client"
  end
end

app/helpers/cinemas_helper.rb
module CinemasHelper
end

app/helpers/clients_helper.rb
module ClientsHelper
end

app/helpers/movies_helper.rb
module MoviesHelper
end

app/helpers/points_helper.rb
module PointsHelper
end

app/helpers/report_helper.rb
module ReportHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/navbar/_navbar.html.erb
<nav class="navbar navbar-expand-lg navbar-dark bg-dark p-3" id="headerNav">
  <div class="container-fluid">
    <a class="navbar-brand d-block d-lg-none" href="#">
      <img src="https://cdn.discordapp.com/attachments/817896477568401478/1048855653076172840/logoP.png" height="80" />
    </a>
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNavDropdown" aria-controls="navbarNavDropdown" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>

    <div class=" collapse navbar-collapse" id="navbarNavDropdown">
      <ul class="navbar-nav mx-auto ">
        <% if user_signed_in?%>
          <% if current_user.is_employee? && current_user.employee.present? %>
            <li class="nav-item active">
              <%= link_to 'Profile',employee_path(current_user.employee.id),class: 'nav-link mx-2' %>
            </li>
            <li class="nav-item active">
              <%= link_to 'Movies report',report_index_path,class: 'nav-link mx-2' %>
            </li>
            <li class="nav-item active">
              <%= link_to 'Points report',report_points_path	,class: 'nav-link mx-2' %>
            </li>
          <% elsif current_user.is_client? %>
            <li class="nav-item active">
              <%= link_to 'Profile',client_path(current_user.client.id),class: 'nav-link mx-2' %>
            </li>
            <li class="nav-item active">
              <%= link_to 'Multiplexes',multiplexes_path,class: 'nav-link mx-2' %>
            </li>
            <li class="nav-item active">
              <%= link_to 'Movies',movies_path,class: 'nav-link mx-2' %>
            </li>
            <li class="nav-item d-none d-lg-block">
              <a class="nav-link mx-2" href="#">
                <img src="https://cdn.discordapp.com/attachments/817896477568401478/1048855653076172840/logoP.png" height="80" />
              </a>
            </li>
            <li class="nav-item active">
              <%= link_to 'Products',products_path,class: 'nav-link mx-2' %>
            </li>
            <li class="nav-item active">
              <%= link_to 'Orders',product_orders_path,class: 'nav-link mx-2' %>
            </li>
            <li class="nav-item active">
              <%= link_to 'My points',points_path,class: 'nav-link mx-2' %>
            </li>
          <% end %>
          <li class="nav-item active">
            <%= button_to 'Log out',destroy_user_session_path, method: :delete, class: 'b1 nav-link mx-2' %>
          </li>
        <% else %>
          <li class="nav-item">
            <%= link_to 'Log in',new_user_session_path, class: 'nav-link mx-2'%>
          </li>
          <li class="nav-item d-none d-lg-block">
            <a class="nav-link mx-2" href="#">
              <img src="https://cdn.discordapp.com/attachments/817896477568401478/1048855653076172840/logoP.png" height="80" />
            </a>
          </li>
          <li class="nav-item">
            <%= link_to 'Sign up',new_user_registration_path,class: 'nav-link mx-2' %>
          </li>
        <% end %>

      </ul>
    </div>
  </div>
</nav>
<style>
    .b1 {
        border: none;
        background: none;
        color: #BBBBBB;
    }
</style>
<style>	@media screen and (min-width:992px){
    .nav-item {
        line-height:80px;
    }
}</style>