config/routes.rb
Rails.application.routes.draw do
  get 'report/index'
  get 'report/points', to: "report#points"
  resources :points
  get 'cinema_place/index'
  get 'cinema_place/show'
  get 'cinema_place/new'
  post '/cinema_places/process', to: "cinema_places#process_place", as: 'process_cinema_place'
  resources :movies do
    resources :califications
  end
  resources :products
  resources :multiplexes do
    resources :cinemas do
      resources :cinema_place
      resources :product_orders, except: [:show, :index]
    end
  end
  resources :product_orders, only: [:show, :index]
  resources :employees
  resources :clients
  get 'welcome/index'
  root to: 'welcome#index'
  devise_for :users, controllers: { registrations: "registrations" }
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
end

app/models/calification.rb
class Calification < Primary2Record
  belongs_to :movie, foreign_key: "movie_id"
end

app/models/cinema.rb
class Cinema < PrimaryRecord
  belongs_to :multiplex, foreign_key: "multiplex_id"
  has_many :cinema_places
  before_create :set_multiplex_number
  has_one :movie, foreign_key: "movie_id"

  def available_places
    cinema_places.where(state: :free).count
  end

  def general_places
    cinema_places.where(state: :free, cinema_place_type: :general).count
  end

  def preference_places
    cinema_places.where(state: :free, cinema_place_type: :preference).count
  end

  private
  def set_multiplex_number
    size = multiplex.cinemas.count
    self.multiplex.update(cinemas_number: size)
  end
end

app/models/cinema_place.rb
class CinemaPlace < PrimaryRecord
  belongs_to :cinema
  has_one :user, foreign_key: "user_id"
  has_many :tickets


  def processing?
    tickets.where(state: :processing).present?
  end

  def preference?
    cinema_place_type == "preference"
  end

  def free?
    !tickets.where(state: [:processing, :busy]).present?
  end

end

app/models/client.rb
class Client < PrimaryRecord
  belongs_to :user
end

app/models/employee.rb
class Employee < PrimaryRecord
  belongs_to :user
  has_one :multiplex, class_name: 'Multiplex',foreign_key: "mutiplex_id"
end

app/models/movie.rb
class Movie < Primary2Record
  has_many :califications
end

app/models/multiplex.rb
class Multiplex < PrimaryRecord
  has_many :cinemas, class_name: "Cinema"

  def set_cinemas_number
    update(cinemas_number: cinemas.count)
  end
end

app/models/point.rb
class Point < PrimaryRecord
  belongs_to :product_order
  belongs_to :client
end

app/models/primary2_record.rb
class Primary2Record < ApplicationRecord
  self.abstract_class = true

  connects_to database: { writing: :primary2 }
end

app/models/primary_record.rb
class PrimaryRecord < ApplicationRecord
  self.abstract_class = true

  connects_to database: { writing: :primary, reading: :primary }
end

app/models/product.rb
class Product < PrimaryRecord
end

app/models/product_item.rb
class ProductItem < PrimaryRecord
  belongs_to :product
  belongs_to :product_order, foreign_key: 'product_order_id', optional: true

  def value
    product.price.to_i
  end
end

app/models/product_order.rb
class ProductOrder < PrimaryRecord
  include AASM
  belongs_to :multiplex
  belongs_to :client
  has_many :product_items
  accepts_nested_attributes_for :product_items, allow_destroy: true, reject_if: :all_blank
  validates_associated :product_items
  has_many :tickets

  aasm column: 'state' do
    state :created, initial: true
    state :paid

    event :paid do
      transitions from: :created, to: :paid
    end
  end

  def paid?
    state == "paid"
  end

  private

end

app/models/ticket.rb
class Ticket < ApplicationRecord
  belongs_to :cinema_place, foreign_key: "cinema_place_id"
  belongs_to :product_order, foreign_key: "product_order_id"
  include AASM
  aasm column: 'state' do
    state :processing, initial: true
    state :busy
    state :finalized

    event :process do
      transitions from: :free, to: :processing
    end

    event :complete do
      transitions from: :processing, to: :busy
    end

    event :clean do
      transitions from: :busy, to: :free
    end

    event :finish do
      transitions to: :finalized
    end
  end
end

app/models/user.rb
class User < PrimaryRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  has_one :client
  has_one :employee

  def full_name
    return "#{name} #{last_name}"
  end

  def has_completed_signed?
    if is_employee?
      return employee.present?
    end
    true
  end

  def is_employee?
    self.role == "Employee"
  end

  def is_client?
    self.role == "Client"
  end
end

app/controllers/employees_controller.rb
class EmployeesController < ApplicationController
  before_action :set_employee, only: %i[ show edit update destroy ]

  # GET /employees or /employees.json
  def index
    @employees = Employee.all
  end

  # GET /employees/1 or /employees/1.json
  def show
  end

  # GET /employees/new
  def new
    @employee = Employee.new
    @multiplexes = Multiplex.all
  end

  # GET /employees/1/edit
  def edit
  end

  # POST /employees or /employees.json
  def create
    @employee = Employee.new(employee_params.merge(user_id: current_user.id, start_date: Date.today))
    respond_to do |format|
      if @employee.save
        format.html { redirect_to employee_url(@employee), notice: "Employee was successfully created." }
        format.json { render :show, status: :created, location: @employee }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @employee.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /employees/1 or /employees/1.json
  def update
    respond_to do |format|
      if @employee.update(employee_params)
        format.html { redirect_to employee_url(@employee), notice: "Employee was successfully updated." }
        format.json { render :show, status: :ok, location: @employee }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @employee.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /employees/1 or /employees/1.json
  def destroy
    @employee.destroy

    respond_to do |format|
      format.html { redirect_to employees_url, notice: "Employee was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_employee
      @employee = Employee.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def employee_params
      params.require(:employee).permit(:user_id, :mutiplex_id, :position, :rol, :start_date, :salary)
    end
end

app/helpers/cinemas_helper.rb
module CinemasHelper
end

app/helpers/clients_helper.rb
module ClientsHelper
end

app/helpers/employees_helper.rb
module EmployeesHelper
end

app/helpers/movies_helper.rb
module MoviesHelper
end

app/helpers/points_helper.rb
module PointsHelper
end

app/helpers/report_helper.rb
module ReportHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/employees/_employee.html.erb
<div id="<%= dom_id employee %>">
</div>

app/views/employees/_form.html.erb
<%= form_with(model: employee) do |form| %>
  <% if employee.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(employee.errors.count, "error") %> prohibited this employee from being saved:</h2>

      <ul>
        <% employee.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :position %>
    <%= form.text_field :position %>
  </div>

  <div class="field">
    <%= form.label :rol %>
    <%= form.text_field :rol %>
  </div>

  <div class="field">
    <%= form.label :salary %>
    <%= form.number_field :salary %>
  </div>

  <div class="field">
    <%= form.label :multiplex_id %>
    <%= form.select(:multiplex_id, Multiplex.all.pluck(:name, :id)) -%>
  </div>


  <div class="field">
    <%= form.submit 'Complete' %>
  </div>
<% end %>

app/views/employees/edit.html.erb
<h1>Editing employee</h1>

<%= render "form", employee: @employee %>

<br>

<div>
  <%= link_to "Show this employee", @employee %> |
  <%= link_to "Back to employees", employees_path %>
</div>

app/views/employees/index.html.erb
<p style="color: green"><%= notice %></p>

<h1>Employees</h1>

<div id="employees">
  <% @employees.each do |employee| %>
    <%= render employee %>
    <p>
      <%= link_to "Show this employee", employee %>
    </p>
  <% end %>
</div>

<%= link_to "New employee", new_employee_path %>

app/views/employees/new.html.erb
<% flash.each do |type, msg| %>
  <div class="alert alert-warning">
    <%= msg %>
  </div>
<% end %>
<h1>New employee</h1>

<%= render "form", employee: @employee, multiplexes: @multiplexes %>

<br>

<div>
  <%= link_to "Back to employees", employees_path %>
</div>

app/views/employees/show.html.erb
<body id="profile">
<div class="page-content page-container" id="page-content">
  <div class="padding">
    <div class="row container d-flex justify-content-center">
      <div class="col-xl-6 col-md-12">
        <div class="card user-card-full">
          <div class="row m-l-0 m-r-0">
            <div class="col-sm-4 bg-c-lite-green user-profile">
              <div class="card-block text-center text-white">
                <div class="m-b-25">
                  <img src="https://img.icons8.com/bubbles/100/000000/user.png" class="img-radius" alt="User-Profile-Image">
                </div>
                <h6 class="f-w-600"><%= @user.name %></h6>
                <p>Web Designer</p>
                <i class=" mdi mdi-square-edit-outline feather icon-edit m-t-10 f-16"></i>
              </div>
            </div>
            <div class="col-sm-8">
              <div class="card-block">
                <h6 class="m-b-20 p-b-5 b-b-default f-w-600">Information</h6>
                <div class="row">
                  <div class="col-sm-6">
                    <p class="m-b-10 f-w-600">Email</p>
                    <h6 class="text-muted f-w-400"><%= @employee.user.email %></h6>
                  </div>
                  <div class="col-sm-6">
                    <p class="m-b-10 f-w-600">Phone</p>
                    <h6 class="text-muted f-w-400"><%= @employee.user.telephone %></h6>
                  </div>
                </div>
                <h6 class="m-b-20 m-t-40 p-b-5 b-b-default f-w-600">Projects</h6>
                <div class="row">
                  <div class="col-sm-6">
                    <p class="m-b-10 f-w-600">Id number</p>
                    <h6 class="text-muted f-w-400"><%= @employee.user.id_number %></h6>
                  </div>
                  <div class="col-sm-6">
                    <p class="m-b-10 f-w-600">Role</p>
                    <h6 class="text-muted f-w-400"><%= @employee.user.role %></h6>
                  </div>
                </div>
                <ul class="social-link list-unstyled m-t-40 m-b-10">
                  <li>
                    <a href="#!" data-toggle="tooltip" data-placement="bottom" title="" data-original-title="facebook" data-abc="true"><i class="mdi mdi-facebook feather icon-facebook facebook" aria-hidden="true"></i></a>
                  </li>
                  <li>
                    <a href="#!" data-toggle="tooltip" data-placement="bottom" title="" data-original-title="twitter" data-abc="true"><i class="mdi mdi-twitter feather icon-twitter twitter" aria-hidden="true"></i></a>
                  </li>
                  <li>
                    <a href="#!" data-toggle="tooltip" data-placement="bottom" title="" data-original-title="instagram" data-abc="true"><i class="mdi mdi-instagram feather icon-instagram instagram" aria-hidden="true"></i></a>
                  </li>
                </ul>
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>
</body>