config/routes.rb
Rails.application.routes.draw do
  get 'report/index'
  get 'report/points', to: "report#points"
  resources :points
  get 'cinema_place/index'
  get 'cinema_place/show'
  get 'cinema_place/new'
  post '/cinema_places/process', to: "cinema_places#process_place", as: 'process_cinema_place'
  resources :movies do
    resources :califications
  end
  resources :products
  resources :multiplexes do
    resources :cinemas do
      resources :cinema_place
      resources :product_orders, except: [:show, :index]
    end
  end
  resources :product_orders, only: [:show, :index]
  resources :employees
  resources :clients
  get 'welcome/index'
  root to: 'welcome#index'
  devise_for :users, controllers: { registrations: "registrations" }
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
end

app/models/calification.rb
class Calification < Primary2Record
  belongs_to :movie, foreign_key: "movie_id"
end

app/models/cinema.rb
class Cinema < PrimaryRecord
  belongs_to :multiplex, foreign_key: "multiplex_id"
  has_many :cinema_places
  before_create :set_multiplex_number
  has_one :movie, foreign_key: "movie_id"

  def available_places
    cinema_places.where(state: :free).count
  end

  def general_places
    cinema_places.where(state: :free, cinema_place_type: :general).count
  end

  def preference_places
    cinema_places.where(state: :free, cinema_place_type: :preference).count
  end

  private
  def set_multiplex_number
    size = multiplex.cinemas.count
    self.multiplex.update(cinemas_number: size)
  end
end

app/models/cinema_place.rb
class CinemaPlace < PrimaryRecord
  belongs_to :cinema
  has_one :user, foreign_key: "user_id"
  has_many :tickets


  def processing?
    tickets.where(state: :processing).present?
  end

  def preference?
    cinema_place_type == "preference"
  end

  def free?
    !tickets.where(state: [:processing, :busy]).present?
  end

end

app/models/client.rb
class Client < PrimaryRecord
  belongs_to :user
end

app/models/employee.rb
class Employee < PrimaryRecord
  belongs_to :user
  has_one :multiplex, class_name: 'Multiplex',foreign_key: "mutiplex_id"
end

app/models/movie.rb
class Movie < Primary2Record
  has_many :califications
end

app/models/multiplex.rb
class Multiplex < PrimaryRecord
  has_many :cinemas, class_name: "Cinema"

  def set_cinemas_number
    update(cinemas_number: cinemas.count)
  end
end

app/models/point.rb
class Point < PrimaryRecord
  belongs_to :product_order
  belongs_to :client
end

app/models/primary2_record.rb
class Primary2Record < ApplicationRecord
  self.abstract_class = true

  connects_to database: { writing: :primary2 }
end

app/models/primary_record.rb
class PrimaryRecord < ApplicationRecord
  self.abstract_class = true

  connects_to database: { writing: :primary, reading: :primary }
end

app/models/product.rb
class Product < PrimaryRecord
end

app/models/product_item.rb
class ProductItem < PrimaryRecord
  belongs_to :product
  belongs_to :product_order, foreign_key: 'product_order_id', optional: true

  def value
    product.price.to_i
  end
end

app/models/product_order.rb
class ProductOrder < PrimaryRecord
  include AASM
  belongs_to :multiplex
  belongs_to :client
  has_many :product_items
  accepts_nested_attributes_for :product_items, allow_destroy: true, reject_if: :all_blank
  validates_associated :product_items
  has_many :tickets

  aasm column: 'state' do
    state :created, initial: true
    state :paid

    event :paid do
      transitions from: :created, to: :paid
    end
  end

  def paid?
    state == "paid"
  end

  private

end

app/models/ticket.rb
class Ticket < ApplicationRecord
  belongs_to :cinema_place, foreign_key: "cinema_place_id"
  belongs_to :product_order, foreign_key: "product_order_id"
  include AASM
  aasm column: 'state' do
    state :processing, initial: true
    state :busy
    state :finalized

    event :process do
      transitions from: :free, to: :processing
    end

    event :complete do
      transitions from: :processing, to: :busy
    end

    event :clean do
      transitions from: :busy, to: :free
    end

    event :finish do
      transitions to: :finalized
    end
  end
end

app/models/user.rb
class User < PrimaryRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  has_one :client
  has_one :employee

  def full_name
    return "#{name} #{last_name}"
  end

  def has_completed_signed?
    if is_employee?
      return employee.present?
    end
    true
  end

  def is_employee?
    self.role == "Employee"
  end

  def is_client?
    self.role == "Client"
  end
end

app/controllers/product_orders_controller.rb
class ProductOrdersController < ApplicationController
  before_action :set_product_order, only: %i[ show edit update destroy ]

  # GET /product_orders or /product_orders.json
  def index
    @product_orders = ProductOrder.where(client_id: current_user.client.id)
  end

  # GET /product_orders/1 or /product_orders/1.json
  def show
  end

  # GET /product_orders/new
  def new
    @current_user = current_user
    @multiplex = Multiplex.find(params[:multiplex_id])
    @cinema = Cinema.find(params[:cinema_id])
    @cinema_places = @cinema.cinema_places
    @product_order = ProductOrder.new
    @product_order.product_items.build
  end

  # GET /product_orders/1/edit
  def edit
    @product_order = ProductOrder.find(params[:id])
    @multiplex = Multiplex.find(params[:multiplex_id])
    @cinema = Cinema.find(params[:cinema_id])
    @cinema_places = @cinema.cinema_places
  end

  # POST /product_orders or /product_orders.json
  def create
    @multiplex = Multiplex.find(params[:multiplex_id])
    @product_order = ProductOrder.new(product_order_params.merge(client_id: current_user.client.id, date: Date.today))
    respond_to do |format|
      if @product_order.save
        format.html { redirect_to edit_multiplex_cinema_product_order_path(id: @product_order.id), notice: "Complete the orden and confirm." }
        format.json { render :show, status: :created, location: @product_order }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @product_order.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /product_orders/1 or /product_orders/1.json
  def update
    products_value = @product_order.product_items.joins(:product).pluck("products.price").sum(&:to_f)
    tickets_value = @product_order.tickets.joins(:cinema_place).pluck("cinema_places.price").sum(&:to_f)
    final_value = products_value + tickets_value

    product_points = (@product_order.product_items.count * 5)
    ticket_points = (@product_order.tickets.count * 10)
    final_points = product_points + ticket_points
    Point.create(count: final_points, product_order_id: @product_order.id, client_id: current_user.client.id, state: :free)
    respond_to do |format|
      if @product_order.update(product_order_params.merge(value: final_value))
        @product_order.paid!
        @product_order.tickets.each{|ticket| ticket.complete! }
        format.html { redirect_to product_order_path(@product_order.id), notice: "Product order was successfully updated." }
        format.json { render :show, status: :ok, location: @product_order }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @product_order.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /product_orders/1 or /product_orders/1.json
  def destroy
    @product_order.destroy

    respond_to do |format|
      format.html { redirect_to product_orders_url, notice: "Product order was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_product_order
      @product_order = ProductOrder.find(params[:id])
    end

    def update_values
      params.require(:product_order).permit(:multiplex_id, :cinema_id ,:client_id, product_items_attributes: [:product_id])
    end


    # Only allow a list of trusted parameters through.
    def product_order_params
      params.permit(:multiplex_id)
    end
end

app/helpers/cinemas_helper.rb
module CinemasHelper
end

app/helpers/clients_helper.rb
module ClientsHelper
end

app/helpers/movies_helper.rb
module MoviesHelper
end

app/helpers/points_helper.rb
module PointsHelper
end

app/helpers/product_orders_helper.rb
module ProductOrdersHelper
end

app/helpers/report_helper.rb
module ReportHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/product_orders/_form.html.erb
<%= form_with(model: product_order) do |form| %>
  <% if product_order.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(product_order.errors.count, "error") %> prohibited this product_order from being saved:</h2>

      <ul>
        <% product_order.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/product_orders/_product_item.html.erb
<%= f.select :product_id, Product.pluck(:name, :id) %>

app/views/product_orders/_product_order.html.erb
<div id="<%= dom_id product_order %>">
</div>

app/views/product_orders/edit.html.erb
<div style="background-color:#1f2122" class="card">
  <h5 class="card-header">Orden</h5>
  <div class="card-body">
    <h5 class="card-title">Detalles</h5>
    <p class="card-text"><strong>Cliente: </strong><%= @current_user.full_name %></p>
    <p class="card-text"><strong>Id: </strong> <%= @current_user.id_number %></p>
    <p class="card-text"><strong>Pelicula: </strong> <%= Movie.find(@cinema.movie_id).name %></p>
    <div style="width: 300px;">
      <p>Escoge tu puesto</p>
      <p>Los rojos son general y los azules preferencial poner un aviso que lo diferencie</p>
      <% unless @product_order.paid? %>
        <%@cinema_places.each do |cinema_place| %>
          <button  onclick="process_place(<%= cinema_place.id %>, <%= @product_order.id %>)"  class="<%= if cinema_place.processing? then "btn btn-danger" elsif cinema_place.free? then 'btn btn-success' else "btn btn-danger" end %>"></button>
        <% end %>
      <% end %>
    </div>
    <p>Agrega productos a tu compra</p>
    <%= form_for(@product_order, url: multiplex_cinema_product_order_path(@multiplex.id, @cinema.id, @product_order.id)) do |f| %>
      <%= f.simple_fields_for :product_items do |p| %>
        <%= render "product_orders/product_item", f: p %>
      <% end %>

      <% if @product_order.state != "paid" %>
        <div class="links">
          <%= link_to_add_association 'Add product', f, :product_items, partial: 'product_orders/product_item' %>
        </div>
        <%= f.submit 'Pagar' %>
      <% else %>
        <p>La orden esta paga</p>
      <% end %>
    <% end %>
  </div>
</div>

<script>
    function process_place(id, order_id){
        let data = {
            id: id,
            order_id: order_id
        }
        fetch('/cinema_places/process',{
            method: 'POST',
            headers: {
                'Content-Type': 'application/json'
            },
            body: JSON.stringify(data)
        })
        window.location.reload();
    }
</script>

app/views/product_orders/index.html.erb
<div style="background-color:#1f2122">
  <table class="table table-bordered table-dark">
    <tr>
      <th>Id</th>
      <th>multiplex Id</th>
      <th>Client Id</th>
      <th>Date</th>
      <th>value</th>
      <th>state</th>
    </tr>
    <% @product_orders.each do |product_order| %>
      <tr>
        <td><%= product_order.id %></td>
        <td><%= product_order.multiplex_id %></td>
        <td><%= product_order.client_id %></td>
        <td><%= product_order.date %></td>
        <td><%= product_order.value %></td>
        <td><%= product_order.state %></td>
      </tr>
    <% end %>
  </table>
</div>

app/views/product_orders/new.html.erb
<div class="card">
  <h5 class="card-header">Orden</h5>
  <div class="card-body">
    <h5 class="card-title">Detalles</h5>
    <p class="card-text"><strong>Cliente: </strong><%= @current_user.full_name %></p>
    <p class="card-text"><strong>Id: </strong> <%= @current_user.id_number %></p>
    <p class="card-text"><strong>Pelicula: </strong> <%= Movie.find(@cinema.movie_id).name %></p>
    <div style="width: 300px;">
      <p>Escoge tu puesto</p>
      <p>Los rojos son general y los azules preferencial poner un aviso que lo diferencie</p>
      <%@cinema_places.each do |cinema_place| %>
        <button onclick="process_place(<%= cinema_place.id %>)" class="<%= if cinema_place.processing? then "btn btn-danger" elsif cinema_place.free? then 'btn btn-success' else "btn btn-danger" end %>"></button>
      <% end %>
    </div>
    <p>Agrega productos a tu compra</p>
    <%= simple_form_for(@product_order, url: multiplex_cinema_product_orders_path) do |f| %>
      <%= f.simple_fields_for :product_items do |p| %>
        <%= render "product_orders/product_item", f: p %>
      <% end %>

      <div class="links">
        <%= link_to_add_association 'Add product', f, :product_items, partial: 'product_orders/product_item' %>
      </div>
      <%= f.submit 'crear' %>
    <% end %>
  </div>
</div>

<script>
  function process_place(id){
      console.log("Asdasdas")
      let data = {
          id: id
      }
      fetch('/cinema_places/process',{
          method: 'POST',
          headers: {
              'Content-Type': 'application/json'
          },
          body: JSON.stringify(data)
      })
      window.location.reload();
  }
</script>

app/views/product_orders/show.html.erb
<div style="background-color:#1f2122">
  <h1>Aqui esta tu orden</h1>
  <h2>Deberia ir toda la orden</h2>
</div>